name: Java8

on:
  push:
    paths:
      - '.github/workflows/java8.yml'

jobs:
  java8:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        update: [x, 265, 262, 252]
      fail-fast: false
      max-parallel: 6
    name: JDK 8.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: zing-actions/setup-java@fix/sync-with-gha-setup-java
      with:
        java-version: 8.0.${{ matrix.update }}
    - name: java -version
      run: java -version
