name: Java13

on:
  push:
    paths:
      - '*/*/java13.yml'

jobs:
  java11:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        update: [x, 4]
      fail-fast: false
      max-parallel: 5
    name: JDK 13.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: zing-actions/setup-java@v1
      with:
        java-version: 13.0.${{ matrix.update }}
    - name: java -version
      run: java -version
