name: Java7

on:
  push:
    paths:
      - '.github/workflows/java7.yml'

jobs:
  java8:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        update: [x, 272, 262]
      fail-fast: false
      max-parallel: 6
    name: JDK 7.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: zing-actions/setup-java@v1
      with:
        java-version: 7.0.${{ matrix.update }}
    - name: java -version
      run: java -version
