name: Java11

on:
  push:
    paths:
      - '*/*/java11.yml'

jobs:
  java11:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        update: [x, 9, 8, 7]
      fail-fast: false
      max-parallel: 5
    name: JDK 11.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: zing-actions/setup-java@fix/sync-with-gha-setup-java
      with:
        java-version: 11.0.${{ matrix.update }}
    - name: java -version
      run: java -version
